[package]
name = "program"
version.workspace = true
edition.workspace = true

[dependencies]
sp1-zkvm = { workspace = true }
solana-sdk.workspace = true
log.workspace = true
sha2.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
share = { path = "../../share" }
