[package]
name = "share"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tiny-keccak.workspace = true
solana-sdk.workspace = true
sled.workspace = true
